# Generated by Django 5.0.6 on 2024-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_sanisette_remove_drinkingfountain_street_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkingfountain',
            name='city',
        ),
        migrations.AddField(
            model_name='drinkingfountain',
            name='district',
            field=models.CharField(default=75, max_length=10),
            preserve_default=False,
        ),
    ]
