# Generated by Django 5.0.6 on 2024-05-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_alter_drinkingfountain_id_alter_sanisette_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingfountain',
            name='fountain_id',
            field=models.CharField(default='2zzza', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanisette',
            name='sanisette_id',
            field=models.CharField(default='eeerd', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drinkingfountain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sanisette',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
