# Generated by Django 5.0.6 on 2024-05-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_drinkingfountain_fountain_id_sanisette_sanisette_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkingfountain',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingfountain',
            name='district',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingfountain',
            name='fountain_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='drinkingfountain',
            name='object_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sanisette',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sanisette',
            name='district',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sanisette',
            name='hours',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sanisette',
            name='sanisette_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sanisette',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
