# Generated by Django 5.0.6 on 2024-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_alter_drinkingfountain_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkingfountain',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sanisette',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
