# Generated by Django 5.0.2 on 2024-05-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0007_alter_drinkingfountain_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi_id', models.CharField(max_length=100, unique=True)),
                ('spot_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('state', models.BooleanField(default=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
