# Generated by Django 5.0.6 on 2024-05-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0008_wifispot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabHIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=100, unique=True)),
                ('lab_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('hours', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
