# Generated by Django 5.0.6 on 2024-05-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_remove_drinkingfountain_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkingfountain',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sanisette',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
