# Generated by Django 5.0.6 on 2024-05-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0011_glassrecyclingtrash_organicwastetrash_sapincollect_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlassRecyclingTrash',
            new_name='RecyclingTrash',
        ),
    ]
