# Generated by Django 5.0.2 on 2024-05-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_alt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_credit',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
