# Generated by Django 5.0.2 on 2024-05-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_cover_alt_alter_event_cover_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_zipcode',
            field=models.CharField(max_length=50),
        ),
    ]
